config/routes.rb
Rails.application.routes.draw do

  get "/route", to: "payments#route"
  get "/buys", to: "payments#buys"	
  get "payments/express"
  get "transactions/checkout"
  
  resources :payments
  resources :deals
  resources :categories
  devise_for :users
  resources :destinations
 get 'welcome/index'
 root 'destinations#index'

 get "/dashboard", to: "welcome#dashboard"

 put "/destinations/:id/publish", to: "destinations#publish"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/partials/_navigation.html.erb
<header>

  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        
        <%= link_to "RupGo", destinations_path, :class=>"navbar-brand" %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <!-- <li><%= link_to "HotDeals", deals_path %></li>
                    <li id="colombia"><a href="#">COLOMBIA</a></li> -->
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#">Action</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li>
        </ul>
        <!-- Form To SEARCH CONTENT -->

        <!-- <form class="navbar-form navbar-left">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Search">
          </div>
          <button type="submit" class="btn btn-default">Submit</button>
        </form> -->


        <ul class="nav navbar-nav navbar-right">
          
          <li id="colombia"><a href="#" >GET TO KNOW COLOMBIA</a></li>
          <li><%= link_to "HotDeals", deals_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "My Cart", route_path %></li>
          

        <% end -%>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">ACCOUNT<span class="caret"></span></a>
            <ul class="dropdown-menu">
            <% if user_signed_in? %>
              
              <li><%= link_to "My Routes", buys_path %></li>
              <li><%= link_to "Close Session", destroy_user_session_path, method: :delete %></li>
               <% else %>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Sign In", new_user_session_path %></li>
              <li><%= link_to "Create Account", new_user_registration_path %></li>
            <% end %>
            </ul>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div>
    <div id="mega_menu" class="container no-list">
      <ul>
        <% @categories.each do  |category| %>
          <li class="col-md-4  category">
                
          <%= link_to category.name,category %> 
                    
          </li> 
        <% end -%>
      </ul>
    </div><!-- /.container-fluid -->
  </nav>

</header>