config/routes.rb
Rails.application.routes.draw do

  get "/route", to: "payments#route"
  get "/buys", to: "payments#buys"	
  get "payments/express"
  get "transactions/checkout"
  
  resources :payments
  resources :deals
  resources :categories
  devise_for :users
  resources :destinations
 get 'welcome/index'
 root 'destinations#index'

 get "/dashboard", to: "welcome#dashboard"

 put "/destinations/:id/publish", to: "destinations#publish"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
before_action :authenticate_admin!, only: [:dashboard]
  def index
  end

  def dashboard
  	@destinations =Destination.all
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/dashboard.html.erb
 <p id="notice"><%= notice %></p>

<h1>Destinations</h1>

<table>
  <thead>
    <tr>
      <th>Place</th>
      <th>Why go</th>
      <th>To do</th>
      <th>Sights</th>
      <th>Festivals</th>
      <th>Sleep</th>
      <th>Eat</th>
      <th>Drink</th>
      <th>Shop</th>
      <th>Around</th>
      <th colspan="3"></th>
    </tr>
  </thead>
 <% @destinations.each do |destination| %>
      <tr>
        <td><%= link_to destination.place, destination %></td>
        <td><%= destination.why_go %></td>
        <td><%= destination.to_do %></td>
        <td><%= destination.sights %></td>
        <td><%= destination.festivals %></td>
        <td><%= destination.sleep %></td>
        <td><%= destination.eat %></td>
        <td><%= destination.drink %></td>
        <td><%= destination.shop %></td>
        <td><%= destination.around %></td>
        <td><%= link_to 'Show', destination %></td>
        <td><%= link_to 'Edit', edit_destination_path(destination) %></td>
        <td><%= link_to 'Destroy', destination, method: :delete, data: { confirm: 'Are you sure?' } %></td>

        <% if destination.may_publish? %>
        <td><%= link_to 'Publicar', "/destinations/#{destination.id}/publish", method: :put, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
      </tr>
    <% end %>

</tbody>
</table>

<br>
<%= link_to 'New Destination', new_destination_path %>

app/views/welcome/index.html.erb
<h1>Welcome to RupGo</h1>