config/routes.rb
Rails.application.routes.draw do

  get "/route", to: "payments#route"
  get "/buys", to: "payments#buys"	
  get "payments/express"
  get "transactions/checkout"
  
  resources :payments
  resources :deals
  resources :categories
  devise_for :users
  resources :destinations
 get 'welcome/index'
 root 'destinations#index'

 get "/dashboard", to: "welcome#dashboard"

 put "/destinations/:id/publish", to: "destinations#publish"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/deal.rb
class Deal < ApplicationRecord
  belongs_to :user
  has_many :payments
  validates :place, presence: true, uniqueness: true
  before_save :default_price
  
  	def default_price
  		self.price ||= 0
	end

	def user_already_paid? user_id
		self.payments.where(state:2).size > 0
	end
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  before_action :set_deal, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show,:index]
  
  # GET /deals
  # GET /deals.json
  def index
    @deals = Deal.all
  end

  # GET /deals/1
  # GET /deals/1.json
  def show
  end

  # GET /deals/new
  def new
    @deal = Deal.new
  end

  # GET /deals/1/edit
  def edit
  end

  # POST /deals
  # POST /deals.json
  def create
    @deal = current_user.deals.new(deal_params)

    respond_to do |format|
      if @deal.save
        format.html { redirect_to @deal, notice: 'Deal was successfully created.' }
        format.json { render :show, status: :created, location: @deal }
      else
        format.html { render :new }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /deals/1
  # PATCH/PUT /deals/1.json
  def update
    respond_to do |format|
      if @deal.update(deal_params)
        format.html { redirect_to @deal, notice: 'Deal was successfully updated.' }
        format.json { render :show, status: :ok, location: @deal }
      else
        format.html { render :edit }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deals/1
  # DELETE /deals/1.json
  def destroy
    @deal.destroy
    respond_to do |format|
      format.html { redirect_to deals_url, notice: 'Deal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_deal
      @deal = Deal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def deal_params
      params.require(:deal).permit(:place, :description, :details, :other_details, :policies_and_fees, :price, :user_id)
    end
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/views/deals/_form.html.erb
<%= form_for(deal) do |f| %>
  <% if deal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(deal.errors.count, "error") %> prohibited this deal from being saved:</h2>

      <ul>
      <% deal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :place %>
    <%= f.text_field :place %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :details %>
    <%= f.text_area :details %>
  </div>

  <div class="field">
    <%= f.label :other_details %>
    <%= f.text_area :other_details %>
  </div>

  <div class="field">
    <%= f.label :policies_and_fees %>
    <%= f.text_area :policies_and_fees %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price, step: "any" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/deals/edit.html.erb
<h1>Editing Deal</h1>

<%= render 'form', deal: @deal %>

<%= link_to 'Show', @deal %> |
<%= link_to 'Back', deals_path %>

app/views/deals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Deals</h1>

<table>
  <thead>
    <tr>
      <th>Place</th>
      <th>Description</th>
      <th>Details</th>
      <th>Other details</th>
      <th>Policies and fees</th>
      <th>Price</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @deals.each do |deal| %>
      <tr>
        <td><%= link_to deal.place, deal %></td>
        <td><%= deal.description %></td>
        <td><%= deal.details %></td>
        <td><%= deal.other_details %></td>
        <td><%= deal.policies_and_fees %></td>
        <td><%= deal.price %></td>
        <td><%= deal.user %></td>
        <td><%= link_to 'Show', deal %></td>
        <td><%= link_to 'Edit', edit_deal_path(deal) %></td>
        <td><%= link_to 'Destroy', deal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Deal', new_deal_path %>

app/views/deals/new.html.erb
<h1>New Deal</h1>

<%= render 'form', deal: @deal %>

<%= link_to 'Back', deals_path %>

app/views/deals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Place:</strong>
  <%= @deal.place %>
</p>

<p>
  <strong>Description:</strong>
  <%= @deal.description %>
</p>

<p>
  <strong>Details:</strong>
  <%= @deal.details %>
</p>

<p>
  <strong>Other details:</strong>
  <%= @deal.other_details %>
</p>

<p>
  <strong>Policies and fees:</strong>
  <%= @deal.policies_and_fees %>
</p>

<p>
  <strong>Price:</strong>
  <%= @deal.price %>
</p>

<p>
  <strong>User:</strong>
  <%= @deal.user %>
</p>

<% if user_signed_in? %>
 <% if @deal.user_already_paid? current_user.id %>
 
 <% else %> 
  <%= render "payments/form", payment: Payment.new, deal: @deal %>
<% end %>
<% end %>

<%= link_to 'Edit', edit_deal_path(@deal) %> |
<%= link_to 'Back', deals_path %>

<div